const data = [
  {
    id: "1",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "crE",
    ansKannada: "ansK",
    ansHindi: "ansK",
  },
  {
    id: "2",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "yes",
    ansKannada: "yes",
    ansHindi: "yes",
    optnKannada: ["yes", "no"],
    optnEnglish: ["yes", "no"],
    optnHindi: ["yes", "no"],
  },
  {
    id: "3",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "3",
    ansKannada: "3",
    ansHindi: "3",
    optnKannada: ["yes", "no", "3", "4"],
    optnEnglish: ["yes", "no", "3", "4"],
    optnHindi: ["yes", "no", "3", "4"],
  },
  {
    id: "4",
    QEnglish: "english q4 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: ["3", "2"],
    ansKannada: ["3", "2"],
    ansHindi: ["3", "2"],
    optnKannada: ["1", "2", "3", "4"],
    optnEnglish: ["1", "2", "3", "4"],
    optnHindi: ["1", "2", "3", "4"],
  },
  {
    id: "5",
    QEnglish: "english q4 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: ["3", "2", "1", "4"],
    ansKannada: ["3", "2", "1", "4"],
    ansHindi: ["3", "2", "1", "4"],
    optnKannada: [
      ["6", "1"],
      ["7", "2"],
      ["8", "3"],
      ["9", "4"],
    ],

    optnEnglish: [
      ["6", "1"],
      ["7", "2"],
      ["8", "3"],
      ["9", "4"],
    ],
    optnHindi: [
      ["6", "1"],
      ["7", "2"],
      ["8", "3"],
      ["9", "4"],
    ],
  },
];
export default data;
