const data = [
  {
    id: "1",
    QEnglish: "1)  how many states are in india ?",
    QKannada: "1)  ಭಾರತದಲ್ಲಿ ಎಷ್ಟು ರಾಜ್ಯಗಳಿವೆ ?",
    QHindi: "1) भारत में कितने राज्य हैं ?",
    ansEnglish: "28",
    ansKannada: "28",
    ansHindi: "28",
  },
  {
    id: "2",
    QEnglish: "2) Bill Gates is the founder of Amazon?",
    QKannada: "2) ಬಿಲ್ ಗೇಟ್ಸ್ ಅಮೆಜಾನ್ ಸಂಸ್ಥಾಪಕರು??",
    QHindi: "2) Amazon के संस्थापक बिल गेट्स हैं ?",
    ansEnglish: "no",
    ansKannada: "ಇಲ್ಲ",
    ansHindi: "नहीं",
    optnKannada: ["ಹೌದು", "ಇಲ್ಲ"],
    optnEnglish: ["yes", "no"],
    optnHindi: ["हां", "नहीं"],
  },
  {
    id: "3",
    QEnglish: "3) When did India become a republic?",
    QKannada: "3) ಭಾರತ ಯಾವಾಗ ಗಣರಾಜ್ಯವಾಯಿತು?",
    QHindi: "3) भारत कब गणतंत्र बना?",
    ansEnglish: "1950",
    ansKannada: "1950",
    ansHindi: "1950",
    optnKannada: ["1935", "1947", "1950", "1961"],
    optnEnglish: ["1935", "1947", "1950", "1961"],
    optnHindi: ["1935", "1947", "1950", "1961"],
  },
  {
    id: "4",
    QEnglish: "4) what is the value of pie?",
    QKannada: "4) ಪೈ ಮೌಲ್ಯ ಏನು??",
    QHindi: "4) पाई का मूल्य क्या है?",
    ansEnglish: [" 3.14", "22/7"],
    ansKannada: [" 3.14", "22/7"],
    ansHindi: [" 3.14", "22/7"],
    optnKannada: ["24/7", " 3.14", "3", "22/7"],
    optnEnglish: ["24/7", " 3.14", "3", "22/7"],
    optnHindi: ["24/7", " 3.14", "3", "22/7"],
  },
  {
    id: "5",
    QEnglish: "5) match the following ",
    QKannada: "5) ಕೆಳಗಿನವುಗಳನ್ನು ಹೊಂದಿಸಿ",
    QHindi: "5) निम्नलिखित को मिलाएं",
    ansEnglish: ["5", "8", "0", "6"],
    ansKannada: ["5", "8", "0", "6"],
    ansHindi: ["5", "8", "0", "6"],
    optnKannada: [
      ["2+3 =", "8"],
      ["7+1 =", "6"],
      ["6-6 = ", "5"],
      ["3+3 =", "0"],
    ],

    optnEnglish: [
      ["2+3 =", "8"],
      ["7+1 =", "6"],
      ["6-6 = ", "5"],
      ["3+3 =", "0"],
    ],
    optnHindi: [
      ["2+3 =", "8"],
      ["7+1 =", "6"],
      ["6-6 = ", "5"],
      ["3+3 =", "0"],
    ],
  },
];
export default data;
