const data = [
  {
    id: "1",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "crE",
    ansKannada: "ansK",
    ansHindi: "ansK",
  },
  {
    id: "2",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "crE",
    ansKannada: "ansK",
    ansHindi: "ansK",
  },
  {
    id: "3",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "crE",
    ansKannada: "ansK",
    ansHindi: "ansK",
  },
  {
    id: "4",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "crE",
    ansKannada: "ansK",
    ansHindi: "ansK",
  },
  {
    id: "5",
    QEnglish: "english q1 ?",
    QKannada: "kannada 1 ?",
    QHindi: "hindhi",
    ansEnglish: "crE",
    ansKannada: "ansK",
    ansHindi: "ansK",
  },
];
export default data;
