export default {
  request: {
    type: "City",
    query: "New York, United States of America",
    language: "en",
    unit: "m",
  },
  location: {
    name: "New York",
    country: "United States of America",
    region: "New York",
    lat: "40.714",
    lon: "-74.006",
    timezone_id: "America/New_York",
    localtime: "2021-12-27 02:51",
    localtime_epoch: 1640573460,
    utc_offset: "-5.0",
  },
  current: {
    observation_time: "07:51 AM",
    temperature: 4,
    weather_code: 116,
    weather_icons: [
      "https://assets.weatherstack.com/images/wsymbols01_png_64/wsymbol_0004_black_low_cloud.png",
    ],
    weather_descriptions: ["Partly cloudy"],
    wind_speed: 22,
    wind_degree: 310,
    wind_dir: "NW",
    pressure: 1019,
    precip: 0,
    humidity: 50,
    cloudcover: 25,
    feelslike: 1,
    uv_index: 1,
    visibility: 16,
    is_day: "no",
  },
};
